# Generated by Django 5.0.7 on 2024-08-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
                ('taskCompleted', models.BooleanField()),
                ('deadline', models.DateField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
