# Generated by Django 5.0.7 on 2024-08-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='task',
            name='taskCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
